version: '3.8'

services:
  docker-diary-api:
    # depends_on: 
    #   - roach
    build:
      context: .
    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet
    ports:
      - 8000:8000
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - TZ = 
    deploy:
      restart_policy:
        condition: on-failure
#   roach:
#     image: cockroachdb/cockroach:latest-v20.1
#     container_name: roach
#     hostname: db
#     networks:
#       - mynet
#     ports:
#       - 5432:5432
#       - 80:8000
#     volumes:
#       - roach:/cockroach/cockroach-data
#     command: start-single-node --insecure

# volumes:
#   roach:

networks:
  mynet:
    driver: bridge